#Gradle
org.gradle.jvmargs=-Xmx4096M -Dkotlin.daemon.jvm.options\="-Xmx4096M"
org.gradle.java.home=/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home
org.gradle.java.installations.paths=/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home

#Kotlin
kotlin.code.style=official

#MPP
kotlin.mpp.stability.nowarn=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.androidSourceSetLayoutVersion=2

#Android
android.useAndroidX=true
android.compileSdk=36
android.targetSdk=36
android.minSdk=24

#Versions
kotlin.version=2.4.10
agp.version=8.13.2
compose.version=1.11.1

#Packaging
compose.desktop.packaging.checkJdkVendor=false

#Libraries
sqlDelight.version=2.3.2
kotlinxDatetime.version=0.8.0
lifecycle.version=2.10.0
coroutinesTest.version=1.11.0
arrow.version=2.2.3
supabase.version=3.7.0
ktor.version=3.2.0
serialization.version=1.9.0
glance.version=1.1.1
